# Filter Class


In [ ]:
import numpy as np

class Filter:
    
    ### constructor takes array which will be filter
    def __init__(self, filterM):
        self.filter = np.array(filterM)
        self.n = self.filter.shape[0]
        self.m = self.filter.shape[1]
        
    ### returns filter
    def get_filter(self):
        return self.filter
    
    ### change filter by delta matrix
    def add_delta(self, delta):
        self.filter += delta

    ### set the value of i,j element of the filter 
    def set(self, i, j, val):
        self.filter[i][j] = val

    ### returns the value of i,j element
    def get(self, i, j):
        return self.filter[i][j]

    ### takes matrix and returns filtered matrix
    def go_filter(self, data):
        resultdata = np.zeros((data.shape[0] - self.n + 1, data.shape[1] - self.m + 1))
        for i in range(data.shape[0] - self.n + 1):
            for j in range(data.shape[1] - self.m + 1):
                resultdata[i][j] = np.sum(self.filter * data[i:i+self.n,j:j+self.m])
        return resultdata
    
    ### takes matrix and poolfilter dimension, returns max-pooled matrix
    def go_maxpool(self, data, n, m):
        resultdata = np.zeros((int(data.shape[0] / n) , int(data.shape[1] / m)))
        for i in range(0, data.shape[0], n):
            for j in range(0, data.shape[1], m):
                print(i,j)
                resultdata[int(i/n)][int(j/m)] = np.max(data[i:i+n, j:j+m])
                
        return resultdata


# Layer Class

In [46]:

class Layer:
    ### constructor takes the list of filters 
    def __init__(self, filters):
        self.filters = filters
        self.matrixes = [] 
    
    ### returns the i-th filter
    def get_filter(self, i):
        return self.filters[i]
    
    ### return the list of filters
    def get_filters(self):
        return self.filters
    
    ### generates list of matrixes, from previous layer's matrixes and it's filters
    def gen_matrixes(self, preMatrixes):
        for filt in self.filters:
            for mat in preMatrixes:
                self.matrixes.append(filt.go_filter(mat))
        
        
    ### returns i-th matrix of our matrixs' list
    def get_matrix(self, i):
        return self.matrix[i]
    
    ### returns list of matrixes
    def get_matrixes(self):
        return self.matrixes
    


# CNN Class

In [ ]:
class CNN:
    ### constructor takes the starting matrix and filters list for each layer
    ### layerFilters is 4D list
    ### a = CNN(ar, )
    def __init__(self, stMatrix, layerFilters):
        self.stMatrix = stMatrix
        self.layers = []
        for layerFilter in layerFilters:
            self.layers.append(Layer(layerFilter))
    
    ### returns all layer objects 
    def get_layers(self):
        return self.layers
    
    ### returns i-th layer
    def get_layer(self, i):
        return self.layers[i]
        
    ### returns flattened np-array for fully connection NL
    def forward_prop(self):
        matrixList = [self.stMatrix]
        for layer in self.layers:
            layer.gen_matrixes(matrixList)
            matrixList = layer.get_matrixes()
            //print(matrixList)
        return self.flatten(matrixList)
            
    ### static method, flattens 3D array
    def flatten(self, matrixList):
        lst = []
        for matrix in matrixList:
            print(matrix,matrix.flatten())
            lst+=(matrix.flatten().tolist())
        return lst
        

In [49]:
cnn = CNN(np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]),[[Filter([[1,1],[1,1]])],[Filter([[2,2],[2,2]]),Filter([[3,3],[3,3]])]])
print(cnn.forward_prop())
#CNN.flatten([np.array([[1,2],[3,4]]),np.array([[1,2,3],[3,4,5]])])

[[1 2]
 [3 4]] [1 2 3 4]
[[1 2 3]
 [3 4 5]] [1 2 3 3 4 5]


[1, 2, 3, 4, 1, 2, 3, 3, 4, 5]

# Dance NL Class

In [ ]:
class Dense:
    
    ### constructor takes parameter's array(flattened array) and answer array(1x10)
    def __init__(self, X, Y):
        self.X = X
        self.Y = Y
        self.theta0 = np.random.randn(self.X.size, 64)
        self.theta1 = np.random.randn(64, 10)
       
    def sigmoid(H):
        return 1/(1+np.exp(-H))
    
    def div_sigmoid(H):
        return np.exp(-H)/((1+np.exp(-H))**2)
    
    def forward_prob(self, z0, theta0, theta1):
        z1 = np.dot(z0, theta0)
        H = np.dot(z1, theta1)
        sh = sigmoid(H)
        return z1, H, sh
    
    def backward_prob(self, z0, z1, H, y, theta1, sh):
        err = (sh-y)*div_sigmoid(H)
        delta_theta1 = np.dot(np.transpose(z1*div_sigmoid(H)),err)
        delta_theta0 = np.dot(np.dot(np.transpose(z0),err),np.transpose(theta1))
        return delta_theta0, delta_theta1
    
    def procdure(self, learnRate):
        z1, H, sh = forward_prob(X, theta0, theta1)
        delta_theta0, delta_theta1 = backward_prob(train, z1, H, y, theta1, sh)

        self.theta0 -= delta_theta0
        self.theta1 -= delta_theta1
            
        ### calc beqas loss and return <3

        #return theta0, theta1
        return r